#=================================================
# Description: Fetch EPG using GitHub Actions
# Lisence: MIT
# Author: slipdaly
#=================================================

name: fetch_epg

on:
  schedule:
    - cron: 10 18 * * *
    - cron: 10 22 * * *
    - cron: 10 04 * * *
    #- cron: 10 09 * * *

  workflow_dispatch:
      # Inputs the workflow accepts.
      inputs:
        name:
          # Friendly description to be shown in the UI instead of 'name'
          description: 'fetch epg'
          # Default value if no value is explicitly provided
          default: 'run'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  fetch_epg:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: '7.4'

      - name: Checkout private source code
        uses: actions/checkout@v3
        with:
          repository: slipdaly/TVproxy
          token: ${{ secrets.ACTIONS_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: tvepg

      - name: Check PHP Version
        working-directory: ./tvepg
        run: |
          php -v
          
      - name: do_fetch_epg
        working-directory: ./tvepg
        run: |
          rm -rf ./deploy/epg/epg.xml.gz ./deploy/epg/epg.xml ./deploy/epg/logs/*.log
          php ./deploy/epg/cron_epg
          echo $(date +%s) > ./deploy/epg/epg_time
          [ -f "./deploy/epg/epg.xml.gz" ] && echo "epgStatus=0" >> $GITHUB_ENV
      
      - name: Checkout slipdaly.github.io
        uses: actions/checkout@v3
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        with:
          repository: slipdaly/slipdaly.github.io
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: pages
      
      - name: copy to pages
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        working-directory: ./pages
        run: |
          cp ../tvepg/deploy/epg/epg.xml.gz ./epg/
          cp ../tvepg/deploy/epg/epg_time ./epg/
          [ -f "./epg/epg.xml.gz" ] && echo "pubStatus=0" >> $GITHUB_ENV
          
      - name: commit to pages  
        if: ${{ env.pubStatus }} == 0 && !cancelled()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./pages
          commit_message: auto commit epg by bot
      
      - name: zip logs
        working-directory: ./tvepg
        run: |
          find ./deploy/epg/logs/ -name "*.log" | xargs -i zip -j -9 ./deploy/epg/fetchLogs.zip {}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: sleep one minute
        run: |
          sleep 1m
          echo "continue task"

      - name: Upload epg file to release
        uses: softprops/action-gh-release@v1
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: v1
          files: |
            ./tvepg/deploy/epg/epg_time
            ./tvepg/deploy/epg/epg.xml.gz
            ./tvepg/deploy/epg/fetchLogs.zip
            
      - name: sleep last one minute
        run: |
          sleep 1m
          echo "continue last step"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          retain_days: 1
          keep_minimum_runs: 3

