#=================================================
# Description: Fetch EPG using GitHub Actions
# Lisence: MIT
# Author: slipdaly
#=================================================

name: fetch_epg

on:
  schedule:
    - cron: 10 18 * * *
    - cron: 10 22 * * *
    - cron: 10 04 * * *
    - cron: 10 09 * * *

  watch:
    types: [ started ]

jobs:
  fetch_epg:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: '7.4'

      - name: Checkout private source code
        uses: actions/checkout@v3
        with:
          repository: slipdaly/TVproxy
          token: ${{ secrets.ACTIONS_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: tvepg

      - name: Check PHP Version
        working-directory: ./tvepg
        run: |
          php -v
          
      - name: do_fetch_epg
        working-directory: ./tvepg
        run: |
          php ./deploy/epg/cron_epg
          echo $(date +%s) > ./deploy/epg/epg_time
          [ -f "./deploy/epg/epg.xml.gz" ] && echo "epgStatus=0" >> $GITHUB_ENV
      - name: Assemble logs artifact
        working-directory: ./tvepg
        run: |
          find ./deploy/epg/logs/ -name "*.log" | xargs -i zip -j -9 ./deploy/epg/fetchLogs.zip {}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload epg file to release
        uses: softprops/action-gh-release@v1
        if: ${{ env.epgStatus }} == 0 && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: v1
          files: |
            ./tvepg/deploy/epg/epg_time
            ./tvepg/deploy/epg/epg.xml.gz
            ./tvepg/deploy/epg/fetchLogs.zip

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          retain_days: 2
          keep_minimum_runs: 3

