#=================================================
# Description: Fetch EPG using GitHub Actions
# Lisence: MIT
# Author: slipdaly
#=================================================

name: testdns

on:
  schedule:
    #- cron: 10 18 * * *
    #- cron: 10 22 * * *
    #- cron: 10 04 * * *
    #- cron: 10 09 * * *

  workflow_dispatch:
      # Inputs the workflow accepts.
      inputs:
        name:
          # Friendly description to be shown in the UI instead of 'name'
          description: 'test timezone'
          # Default value if no value is explicitly provided
          default: 'test'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  testdns:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dns pre
        run: |
          echo "currentTime is $(date)"
          nslookup portal.gcable.cn
      - name: setTimeZone
        uses: szenius/set-timezone@v1.1
        with:
         timezoneLinux: "Asia/Shanghai"

      - name: Check dns after
        run: |
          echo "currentTime is $(date)"
          nslookup portal.gcable.cn
          curl --connect-timeout 10 -o /dev/null -s -w time_namelookup:"	"%{time_namelookup}" "time_connect:"		"%{time_connect}" "time_appconnect:"	"%{time_appconnect}" "time_pretransfer:"	"%{time_pretransfer}" "time_starttransfer:"	"%{time_starttransfer}" "time_total:"		"%{time_total}" "time_redirect:"		"%{time_redirect}" " http://epg.slipdaly.eu.org/
          
          echo "end"
         