#=================================================
# Description: Fetch EPG using GitHub Actions
# Lisence: MIT
# Author: slipdaly
#=================================================

name: testtimeZone

on:
  schedule:
    - cron: 10 18 * * *
    - cron: 10 22 * * *
    - cron: 10 04 * * *
    #- cron: 10 09 * * *

  workflow_dispatch:
      # Inputs the workflow accepts.
      inputs:
        name:
          # Friendly description to be shown in the UI instead of 'name'
          description: 'test timezone'
          # Default value if no value is explicitly provided
          default: 'test'
          # Input has to be provided for the workflow to run
          required: true

jobs:
  testtimeZone:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check zone pre
        run: |
          echo "currentTime is $(date)"

      - name: Checkout
        uses: szenius/set-timezone@v1.1
        with:
         timezoneLinux: "Asia/Shanghai"

      - name: Check zone after
        run: |
          echo "currentTime is $(date)"
         

